<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-802VLA7" failures="1" tests="3" name="Login_Validations" time="38.455" errors="0" timestamp="2024-07-06T13:38:22 IST">
  <testcase classname="EcommerceProject.Test.Loginexecution" name="loginTest1" time="3.985"/>
  <testcase classname="EcommerceProject.Test.Loginexecution" name="loginTest2" time="2.049"/>
  <testcase classname="EcommerceProject.Test.Loginexecution" name="loginTest3" time="2.965">
    <failure type="java.lang.AssertionError" message="expected [The credentials provided are incorrect] but found [No customer account found]">
      <![CDATA[java.lang.AssertionError: expected [The credentials provided are incorrect] but found [No customer account found]
at EcommerceProject.Test.Loginexecution.loginTest3(Loginexecution.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginTest3 -->
</testsuite> <!-- Login_Validations -->
